# Matrix Operations

In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

### Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.31432334 0.61846776 0.32435101]
 [0.41379465 0.91522129 0.78458499]
 [0.96263494 0.85790349 0.4560184 ]]


In [ ]:
# creating matrix with random integers

In [7]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[30 33 34 73 62]
 [68 40 70 36 88]
 [ 1 71 24 70 80]
 [ 0 37 83 15 18]]


In [8]:
#Matrix with all the values as 1
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

In [9]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [10]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


### Null Matrix or Zero Matrix

In [11]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Identity Matrix

In [19]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Transpose of a MATRIX

In [13]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[17  5 26 83 76]
 [36 38 17 49  8]
 [94 45 86 67 15]
 [ 7 15  5 56 31]]


In [14]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[17 36 94  7]
 [ 5 38 45 15]
 [26 17 86  5]
 [83 49 67 56]
 [76  8 15 31]]
